
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DeWaaiBeheer
{

    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {

        public int ID { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public string Date { get; set; }

        public int Price { get; set; }

        public int Amount { get; set; }

        public string Color { get; set; }

        public Nullable<System.DateTime> Created { get; set; }

        public Nullable<System.DateTime> Updated { get; set; }

        public int FleedID { get; set; }

    public int Status { get; set; }

    }

}
