//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeWaaiBeheer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntityFramework : DbContext
    {
        public EntityFramework()
            : base("name=EntityFramework")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> Users { get; set; }
        public DbSet<BookedCursu> BookedCursus { get; set; }
        public DbSet<Cours> Courses { get; set; }
        public DbSet<Fleet> Fleets { get; set; }
        public DbSet<Instructor> Instructors { get; set; }
        public DbSet<InstructorsAvailability> InstructorsAvailabilities { get; set; }
        public DbSet<Invoice> Invoices { get; set; }
    }
}
