
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DeWaaiBeheer
{

using System;
    using System.Collections.Generic;
    
public partial class Invoice
{

    public string ID { get; set; }

    public int UserID { get; set; }

    public int InstructorID { get; set; }

    public int CourseID { get; set; }

    public string Status { get; set; }

    public int Year { get; set; }

    public int Booking_month { get; set; }

}

}
