//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeWaaiBeheer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registrations
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string InvoiceID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string Status { get; set; }
        public short Year { get; set; }
        public int Booking_month { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public int Accepted { get; set; }
        public System.DateTime Date { get; set; }
    }
}
